// Auto-generated by OpenLane
module dual_sensor_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_10mhz,
  input rst_n,
  output srf_trig,
  input srf_echo,
  inout i2c_sda,
  inout i2c_scl,
  output pwr_ctrl,
  output uart_tx_pin,
  output[2:0] led_status
);
endmodule
